### PR TITLE
chore(#22): update services

### LINKED ISSUE #22: New services need to be mapped
These new services need to be added to the mapping:

1. `CHP: "PS Community Hosting Program", // 73`
1. `DRP: "PS Distribution Response Program", // 77`
1. `ED: "Education grant", // 79`
1. `UCYDR: "Unaccompanied Children and Youth Department Reception", // 76`
1. `UCYNCN: "UCY Naimo Center Nursery", // 78`
1. `YMPP: "Young Mothers Psychosocial Program", // 75`

Here: https://github.com/Beamanator/RIPS-Auto-Import-CExt/blob/5164c8117f3e612626d062620e2955bc3e40463d/js/Utils.js#L242

### PR DESCRIPTION
**Pull request by Beamanator**
Closes #22

### CODE REVIEW

**Comment by Beamanator** [comment]
@lebombastic You're the RIPS guy, maybe you want to chat about chrome extensions some day? 🤔 😅

**Comment by lebombastic** [comment]
> @lebombastic You're the RIPS guy, maybe you want to chat about chrome extensions some day? 🤔 😅

sure big boss, i never got time to look through the scripts, maybe it's time! hope you made some comments haha

**Comment by Beamanator** [comment]
> sure big boss, i never got time to look through the scripts, maybe it's time! hope you made some comments haha

I sure did sir! However... Probably not enough :D And I think I used Angular 1 for the interface, so it has to be a bit ugly 😄

**Comment by Beamanator** [comment]
Oof angular 1.6.1 haha https://github.com/Beamanator/RIPS-Auto-Import-CExt/blob/master/js/min/angular.min.js

**Pull request merged**
